version: "3.2"
services:
  duplicacy:
    image: saspus/duplicacy-web:latest
    hostname: srv.ajil.ch
    restart: unless-stopped
    environment:
      USR_ID: 0
      GRP_ID: 0
      TZ: Europe/Zurich
      DWE_PASSWORD: ${DWE_PASSWORD}
    ports:
      - "3875:3875"
    volumes:
      - /home:/backuproot
      - /root/id_rsa:/id_rsa
