version: "3.2"
services:
  tailscale:
    image: tailscale/tailscale:latest
    environment:
      TS_AUTHKEY: ${TAILSCALE_AUTHKEY}
    network_mode: host
    restart: unless-stopped
  duplicacy:
    image: saspus/duplicacy-web:latest
    hostname: srv.ajil.ch
    restart: unless-stopped
    environment:
      USR_ID: 0
      GRP_ID: 0
      TZ: Europe/Zurich
      DWE_PASSWORD: ${DWE_PASSWORD}
    ports:
      - "3875:3875"
    volumes:
      - /home:/backuproot
      - /home/muy/.ssh/id_rsa:/id_rsa
